apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.arch | default "amd64" }}
          imagePullPolicy: Always
          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bot.fullname" . }}-secret
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

